### ISSUE TITLE
ESP32 play music from FS

### ISSUE THREAD

**Issue by fafiunal** [DFRobot/DFRobot_MAX98357A#1]
Can I play music data from file system for ESP32 with this library?

**Comment by qsjhyy** [comment]
This library currently allows playing audio files from an external memory card on the ESP32. You can try making some modifications, and it should be able to meet your needs.
![image](https://github.com/DFRobot/DFRobot_MAX98357A/assets/78136558/03ac53fe-fbeb-4719-a058-f50e1b113135)

**Comment by qsjhyy** [comment]
Due to a lack of further communication for an extended period, this issue has been closed. If there is a need in the future, it can be reopened at any time.
